### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by httpdispatch** [comment]
Thank you very much. Can you please also translate these files? 
https://github.com/httpdispatch/MissedNotificationsReminder/blob/master/app/src/v14/res/values/strings.xml
https://github.com/httpdispatch/MissedNotificationsReminder/blob/master/app/src/v18/res/values/strings.xml

**Comment by Vistaus** [comment]
You're welcome :) What do I have to translate in those files? They have a very different formatting and I don't really see what to translate.

**Comment by Vistaus** [comment]
You're welcome :) I just pushed a commit with translation of those files.

**Comment by httpdispatch** [comment]
Thanks a lot, i will release this soon

**Pull request merged**
