### PR TITLE
Add settings for number of reminder repetitions and implement this feature

### PR DESCRIPTION
**Pull request by rryk**
This also renames Reminder Interval section into Reminder Settings and
changes names of corresponding classes and files.

### CODE REVIEW

**Comment by httpdispatch** [comment]
Thank you very much for the pull request. The limit number of repeats feature has been requested many times so users should be happy with it. I'll try to find a time to review, merge and test pull request and release new version in the next week.

**Comment by rryk** [comment]
Thanks. I have another feature in the pipeline coming after this, but not sure how to add it to a separate pull request... if I push it to master it get automatically added to this... so I guess I'll push it into a separate branch for now

**Comment by rryk** [comment]
This change will address https://github.com/httpdispatch/MissedNotificationsReminder/issues/9.

**Comment by httpdispatch** [comment]
Released the implemented feature. Thank you very much for the contribution. Only one minor fix has been applied https://github.com/httpdispatch/MissedNotificationsReminder/commit/7a6b1ebe3a87d1b9c65ec4f2f90a0980a0be1f70

**Comment by rryk** [comment]
Awesome. Thanks.

**Pull request merged**
